name: Coolhand-Ruby CI
on: [push]
jobs:
  specs:
    runs-on: ubuntu-latest

    container:
      image: ruby:3.4.2-bookworm

    env:
      COOLHAND_ENV: test
      COOLHAND_API_ENDPOINT: https://coolhand_api_endpoint
      COOLHAND_API_KEY: coolhand_api_key-xxx-yyy-zzz
      COOLHAND_SILENT: true
      COOLHAND_OPENAI_ADDRESS: open-ai-host
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

    steps:
      - name: Install Git LFS
        run: |
          apt-get update
          apt-get install -y git-lfs
          git lfs install

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-ruby-3.4.2-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-ruby-3.4.2-

      - name: Bundle config
        run: |
          bundle config path vendor/bundle
          bundle config jobs 4
          bundle config retry 3

      - name: Install Ruby dependencies
        run: bundle install
      - name: Run specs
        run: bundle exec rspec spec
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Ensure minimum coverage
        run: |
          coverage=$(cat coverage/.last_run.json | jq '.result.line')
          if (( $(echo "$coverage < 70" |bc -l) )); then exit 1; fi

  rubocop:
    runs-on: ubuntu-latest

    container:
      image: ruby:3.4.2-bookworm

    steps:
      - name: Install Git LFS
        run: |
          apt-get update
          apt-get install -y git-lfs
          git lfs install

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
      - name: Mark repo as safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-ruby-3.4.2-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: | 
            ${{ runner.os }}-gems-ruby-3.4.2-
      - name: Bundle config
        run: |
         bundle config path vendor/bundle
         bundle config jobs 4
         bundle config retry 3
      - name: Install Ruby dependencies
        run: bundle install
      - name: Run Rubocop
        run: bundle exec rubocop